apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-website-deployment
  labels:
    app: html-website
spec:
  replicas: 2  # You can adjust this based on your needs
  selector:
    matchLabels:
      app: html-website
  template:
    metadata:
      labels:
        app: html-website
    spec:
      containers:
      - name: html-website
        image: aksregistrydevops.azurecr.io/aksregistrydevops:${IMAGE_TAG}  # This will be replaced by the actual image tag during Jenkins deployment
        ports:
        - containerPort: 80  # Nginx serves content on port 80
      imagePullSecrets:
      - name: acr-secret  # Ensure this is configured for your Azure Container Registry
