apiVersion: v1
kind: Service
metadata:
  name: html-website-service
spec:
  selector:
    app: html-website
  ports:
    - protocol: TCP
      port: 80          # The port on which the service will be exposed
      targetPort: 80     # The port on which the container is listening (Nginx default)
  type: LoadBalancer     # Exposes the service externally using a cloud provider's LoadBalancer
