apiVersion: v1
kind: Service
metadata:
  name: cluster-test-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80  # Port accessible externally
      targetPort: 8000  # Port your application listens on
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer
